import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sign in',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className="white-bg-login" lang="en">
      <head>
        <link rel="SHORTCUT ICON"
          href="https://aligarhonline.edu.pk/Online/uploads/images/9abc661af2ca2f446864ef70c7b56a0101e2f6dddb393fc2d316316b211fcfd5c2035ba09334189e99b570e243ee540c0f0337aa59827b71c5c167556d1cbb94.png" />
        <link href="https://aligarhonline.edu.pk/Online/assets/bootstrap/bootstrap.min.css" rel="stylesheet"
          type="text/css" />
        <link href="https://aligarhonline.edu.pk/Online/assets/fonts/font-awesome.css" rel="stylesheet" type="text/css" />
        <link href="style.css" rel="stylesheet" />
        <link href="https://aligarhonline.edu.pk/Online/assets/inilabs/themes/purple/inilabs.css" rel="stylesheet"
          type="text/css" />
        <link href="https://aligarhonline.edu.pk/Online/assets/inilabs/responsive.css" rel="stylesheet" type="text/css" />
      </head>
      <body className={[inter.className, 'white-bg-login']}>{children}</body>
    </html>
  )
}
